export const ACTION_TYPE={
    SET_USER:"SET_USER",
    SET_LOGOUT:"SET_LOGOT",
    SET_BASKET:'SET_BASKET',
    UPDATE_BASKET:"UPDATE_BASKET",
    SET_DELETE_CARD_BASKET:"SET_DELETE_CARD_BASKET",
    SET_SEARCH_PRODUCTS:" SET_SEARCH_PRODUCTS"
}